### ISSUE TITLE
[Auth] parse error

### ISSUE THREAD

**Issue by mikecastrodemaria** [frachop/hubic-backup#17]
Hi,

I try use it, but get this error :
[Auth] parse error: can't find 'type="hidden" name="oauth" value="'. Application will now exit.

Do you have an idea ?
Thanks

**Comment by frachop** [comment]
Hi,

The problem comes from the parsing of the auth web page:

![hubic auth web page](https://cloud.githubusercontent.com/assets/4104766/14701697/e20a7eae-07a6-11e6-875e-8d7f13200246.png)

I need to parse it because hubic do not allow "blind auth".  ( technically, hubic doesn't allow "_grant_type=password_" while authentification)
I can't figure out why your request response can't be parsed. I will have to change this part of code the day hubic will change their auth page. 
Could you tell me more aubout your configuration, and may be the country from where you do the request ?
